export interface IUsuarioProps {
    criarUsuario: boolean,
    nome: string,
    sobrenome: string,
    dataNascimento:string,
    sociedade: string,
    tipoDocumento1: string,
    documento1: string,
    tipoDocumento2: string,
    documento2: string,
    documentosDTO: string,
    email: string,
    nomeTratamento: string,
    profissao: string,
    telefone: string,
    telefone2: string,
    grupoPessoa: string,
    fotoFacial: string,
}
export interface IUsuarioUPDATEProps {
    criarUsuario?: boolean,
    nome?: string,
    sobrenome?: string,
    dataNascimento?:string,
    sociedade?: string,
    tipoDocumento1?: string,
    documento1?: string,
    tipoDocumento2?: string,
    documento2?: string,
    email?: string,
    nomeTratamento?: string,
    profissao?: string,
    telefone?: string,
    telefone2?: string,
    grupoPessoa?: string,
    fotoFacial: string,
}
export interface IUsuarioDELProps {
    email: string
}